name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group:
    "${{github.workflow}} @ ${{github.pull_request.head.label || github.head_ref
    || github.ref}}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3

      - name: Install Inkscape
        if: runner.os == 'Linux'
        run: sudo apt install inkscape

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Packages and Tools
        run: |
          npm install
          npm install --global vsce

      - name: Check Code Format
        run: npx prettier --check .

      - name: Run Tests on Linux
        if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum npm test

      - name: Run Tests on Windows & MacOS
        if: runner.os != 'Linux'
        run: npm test

      - name: Create a VSIX Package
        if: runner.os == 'Linux'
        run: vsce package

      - name: Package Test
        if: runner.os == 'Linux'
        run: ./src/test/package_test.sh
